config/routes.rb
Rails.application.routes.draw do

get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
root 'homes#new'
resources :users 
resources :sessions

get "new/event" => "events#new", :as => "new"
post "new/event" => "events#create", :as => "create"
get 'new/event/:id' => 'events#edit', :as => 'edit'

put 'new/event/:id' => 'events#update', :as => 'update'
delete 'new/event/delete/:id' => 'events#destroy', :as => 'destroy'

end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :owner, class_name: "User"
	has_many :invitations
	has_many :invitees, :through => :invitations, foreign_key: :invitee_id
	
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
	belongs_to :invitee, class_name: "User"
	# belongs_to :inviter, class_name: "User"
	belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events, foreign_key: :owner_id
  # has_many :invitations, foreign_key: :invitee_id

	 # attr_accessor :firstname, :lastname, :username, :phnumber, :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  PASSWORD_FORMAT = /\A
  (?=.{8,})          # Must contain 8 or more characters
  (?=.*\d)           # Must contain a digit
  (?=.*[a-z])        # Must contain a lower case character
  (?=.*[A-Z])        # Must contain an upper case character
  (?=.*[[:^alnum:]]) # Must contain a symbol
/x
validates :password, 
  format: {with: PASSWORD_FORMAT}
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  helper_method :current_user

private

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	# before_action :find_owner, only:[:edit]
	# before_action :find_user, only:[:create]

	def new
		@event=Event.new
		@events=Event.all
		@user_names=User.all
		# @event = event.find_by_id(params[:id])

	end
	def create
		# binding.pry
        @event = Event.new(event_params)
        # binding.pry
		@event.owner_id=current_user.id

		@event.save
		params['role_ids'].each do |a|
			@invitation = Invitation.new
			@invitation.inviter_id = current_user.id
			@invitation.invitee_id = a
			@invitation.event_id = @event.id
			@invitation.save
		end
		redirect_to create_path
	end

	def edit
		@event = Event.find_by_id(params[:id])
		@user_names=User.all
		
	end
	def update
		# binding.pry
		@event = Event.find_by_id(params[:id])
		@event.update_attributes(event_params)
		redirect_to new_path
	end
	def destroy
		@event = Event.find_by_id(params[:id])
		@event.destroy
		redirect_to new_path
	end
	private
	def event_params
		params.require(:event).permit(:event_title,:venu, :date,:discription,:invitees,:status)
	end
	# def find_owner
	# 	@owner =  Event.find_by_owner_id(params[:owner_id])
	# end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def new

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
end

def create
  user = User.authenticate(params[:email], params[:password])
  if user
    session[:user_id] = user.id
    session[:user_firstname] = user.firstname
    redirect_to new_path, :notice => "Logged in as #{session[:user_firstname]} "
  else
    flash.now.alert = "Invalid email or password"
    render "new"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out!"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  @user = User.new
end

def create
  # binding.pry
  @user = User.new(user_params)
  if @user.save
    redirect_to log_in_path, :notice => "Signed in!"
  else
    render "new"
  end
end

private
	def user_params
  # binding.pry

		params.require(:user).permit(:firstname,:lastname,:username,:email,:phnumber,:password,:password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<div class="container">
<%if current_user.id == @event.owner_id%>
<%= form_for :event, url: update_path(@event), method: :put do |f|%>

 <p>
    Event<br />
    <%= f.text_field :event_title %>
  </p>
  <p>
  Venu<br/>
    <%= f.text_field :venu %>
  </p>
  <p>
  Date  <br />
    <%= f.date_field :date %>
  </p>
  <p>
  Description <br />
    <%= f.text_area :discription %>
  </p>
  <p>
            Invitees:<br/>
               </br>
            <%@user_names.each do |role| %>
              <%= check_box_tag 'role_ids[]',role.id-%>
                <%= role.firstname -%><br/>
            <%end%>
            </p>
          <p>
  <br/>
    Status:<br/>  
    <%= f.select :status, ['open', 'closed']%></br></br></br>
  </p>
  <button type="button" style="float:left;"><%= link_to 'Destroy Event', destroy_path(f),
method: :delete,
data: {confirm: 'Are you sure?'}%></button>
  <p class="button"><%= f.submit %></p>

<%end%>

<%else%>
<%= form_for :event, url: update_path(@event), method: :put do |f|%>


 <p>
    Event<br />
    <%= f.text_field :event_title, :disabled => true %>
  </p>
  <p>
  Venu<br/>
    <%= f.text_field :venu, :disabled => true %>
  </p>
  <p>
  Date  <br />
    <%= f.date_field :date, :disabled => true %>
  </p>
  <p>
  Description <br />
    <%= f.text_area :discription,:disabled => true %>
  </p>
  <p>
  Invitees:<br/>
     </br>
    <%= f.text_field :invitees,:disabled => true %>
  </p>
  <p>
  <br/>
    Status:<br/>  
    <%= f.select :status, ['open', 'closed'], :disabled => true%></br></br></br>
  </p>

  <p class="button"><%= f.submit %></p>
  <%end%>
  <%end%>
  </div>

app/views/events/new.html.erb
<div class="container">
  <!-- Trigger the modal with a button -->
  <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Create New Event</button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Create Event</h4>
        </div>
        <div class="modal-body">
          <%= form_for :event do |f| %>
          <p>
            Event<br />
            <%= f.text_field :event_title %>
          </p>
          <p>
          Venu<br/>
            <%= f.text_field :venu %>
          </p>
          <p>
          Date  <br />
            <%= f.date_field :date %>
          </p>
          <p>
          Description <br />
            <%= f.text_area :discription %>
          </p>
          <p>
            Invitees:<br/>
               </br>
            <%@user_names.each do |role| %>
              <%= check_box_tag 'role_ids[]',role.id-%>
                <%= role.firstname -%><br/>
            <%end%>
            </p>
          <p>
            Status :  
            <%= f.select :status, ['open', 'closed']%></br></br></br>
          </p>
          <p class="button"><%= f.submit %></p>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
  </div>
</div>
</div>


  <div class="row">
  <div class="col-sm-5">
  <% @events.each do |event| %>

    <div class="row" style="background-color:#D3D3D3 ; margin:5px; padding:20px">
    <label style="color:green">Event:</label> <%= event.event_title %><br>
    <label style="color:green">Venu: </label> <%= event.venu %>
    


    


    <div class="container1">

  <!-- Trigger the modal with a button -->

  <a data-toggle="modal" data-target="#myModal-<%= event.id%>">Participants</a>
  <%= link_to '| Edit Profile', edit_path(event) %> 

  <!-- Modal -->
  <div id="myModal-<%= event.id%>" class="modal fade" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"></h4>
        </div>
        <div class="modal-body">
        <% event.invitations.each do |var|%>
      <% a = var.invitee_id%>
      <% var1 = User.find_by_id(a)%>
      <%= var1.firstname%> <br/>
    <%end%>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
  
  </div>       

  </div>
 <% end %>

</div>

<div class="col-sm-7">

<%= form_for :event do |f| %>
  
  <p>
    Event<br />
    <%= f.text_field :event_title %>
  </p>
  <p>
  Venu<br/>
    <%= f.text_field :venu %>
  </p>
  <p>
  Date  <br />
    <%= f.date_field :date %>
  </p>
  <p>
  Description <br />
    <%= f.text_area :discription %>
  </p>
    <p>
  <br/>
    Status:<br/>  
    <%= f.select :status, ['open', 'closed']%></br></br></br>
  </p>
  <a href="#"><p class="button"><%= f.submit %></p></a>
<% end %>
</div>
</div>

app/views/homes/new.html.erb
<div class="row">
<div class="col-sm-4"></div>
<div class="col-sm-5">
<%= image_tag("star.jpg") %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventsScheduling</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
<div class="container-fluid">
 <div class="navbar-header">
   <a class="navbar-brand" href="#"><%= image_tag("icon.png") %></a>
 </div>
 
 <ul class="nav navbar-nav navbar-right">
  <% if current_user %>
  <li><%= link_to "Log out", log_out_path %></li>
   Logged in as: <%= current_user.firstname %>
    <% else %>

   <li> <%= link_to "Sign Up", sign_up_path %></li>
   <li> <%= link_to "log In", log_in_path %></li>
  <% end %>

 </ul>
</div>
</nav>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<div class="row">
<div class="col-sm-4"></div>
<div class="col-sm-8">
<br><h1>Sign Up</h1>

<%= form_for( @user, url: users_path) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    Name*<br />
    <%= f.text_field :firstname %>
  </p>
  <p>
  Email*<br/>
    <%= f.text_field :email %>
  </p>
  <p>
  Password*  <br />
    <%= f.password_field :password %>
  </p>
  <p>
  Confirm Password*  <br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>
</div>
</div>